

asc-table-slide-time = 4.04
asc-first-rise-time = 5.05
asc-enbloaten-time = 2.0
asc-before-preso-hold-time = 0.5
asc-presentation-time = 3.0
asc-after-preso-hold-time = 0.5
asc-ensvelten-time = 1.5
asc-second-rise-time = 6.06
